<?php // this is an autogenerated file - do not edit (created Tue, 12 Jul 2011 09:05:05 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'spriebsch\\streamwrapper\\exception' => '/Exception.php',
            'spriebsch\\streamwrapper\\streamwrapper' => '/StreamWrapper.php',
            'spriebsch\\streamwrapper\\streamwrapperinterface' => '/StreamWrapperInterface.php',
            'spriebsch\\streamwrapper\\streamwrapperproxy' => '/StreamWrapperProxy.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
